"""العربية (hand-written, Modern Standard Arabic, simple register)."""
UI = {
'tagline': 'مساعدك في المزرعة. يعمل بدون إنترنت.', 'chooseLang': 'اختر لغتك', 'start': 'ابدأ', 'back': 'رجوع', 'close': 'إغلاق', 'loading': 'جارٍ التحميل…',
'error': 'حدث خطأ ما. حاول مرة أخرى.',
'home.scan': 'افحص نباتي', 'home.scanSub': 'صوّر ورقة نبات', 'home.prices': 'أسعار المحاصيل', 'home.pricesSub': 'بكم سيُباع محصولي؟',
'home.rain': 'توقعات المطر', 'home.rainSub': 'هل ستمطر في الأشهر القادمة؟', 'home.settings': 'الإعدادات', 'home.offlineReady': 'جاهز: يعمل بدون إنترنت', 'home.offlinePrep': 'جارٍ حفظ البيانات للاستخدام دون اتصال…',
'scan.title': 'افحص نباتي', 'scan.mt': 'عرض الترجمة الآلية (غير مراجَعة)', 'scan.which': 'ما النباتات التي يمكنني فحصها؟', 'scan.tip1': 'ضع ورقة واحدة في المنتصف', 'scan.tip2': 'استخدم ضوء النهار',
'scan.tip3': 'أمسك الهاتف بثبات', 'scan.take': 'التقط صورة', 'scan.gallery': 'اختر صورة', 'scan.loading': 'جارٍ فحص نباتك…', 'scan.firstTime': 'جارٍ التجهيز (أول مرة فقط)…',
'scan.retake': 'التقط صورة أخرى', 'scan.notPlant': 'هذه ليست ورقة نبات', 'scan.unsure': 'لست متأكدًا', 'scan.crop': 'النبات', 'scan.healthy': 'سليم', 'scan.sick': 'يحتاج إلى عناية',
'scan.sure.high': 'متأكد جدًا', 'scan.sure.mid': 'متأكد إلى حدّ ما', 'scan.sure.low': 'غير متأكد كثيرًا', 'scan.maybe': 'قد يكون أيضًا', 'scan.what': 'ما هذا؟', 'scan.treat': 'ماذا تفعل',
'scan.prevent': 'كيف تقي منه', 'scan.machine': 'ترجمة بالحاسوب. يُرجى استشارة خبير زراعي.', 'scan.noModel': 'نموذج النباتات غير مثبّت في هذا الإصدار.',
'price.title': 'أسعار المحاصيل', 'price.in3m': 'خلال 3 أشهر', 'price.expected': 'المتوقع', 'price.place': 'مكاني', 'price.crop': 'اختر محصولًا', 'price.search': 'ابحث عن محصول',
'price.now': 'السعر الآن', 'price.perKg': 'للكيلوغرام', 'price.perL': 'للتر', 'price.next': 'السعر المتوقع في الأشهر القادمة', 'price.range': 'النطاق المحتمل', 'price.up': 'يُتوقع أن يرتفع السعر',
'price.down': 'يُتوقع أن ينخفض السعر', 'price.flat': 'يُتوقع أن يبقى السعر كما هو', 'price.best': 'أفضل شهر للبيع', 'price.where': 'أين تبيع قريبًا', 'price.km': 'كم',
'price.updated': 'سعر شهر', 'price.currency': 'اعرض الأسعار بعملة', 'price.err': 'كانت التوقعات السابقة تخطئ بنحو', 'price.noData': 'لا توجد أسعار لهذا البلد بعد.',
'price.setPlace': 'اختر مكانك أولًا', 'price.buyers': 'من يشتري من بلدك', 'price.prod': 'قيمة الإنتاج خلال 5 سنوات',
'price.disclaimer': 'التوقع تخمين مبني على الأسعار السابقة. تحقق من السوق قبل البيع.',
'place.title': 'اختر مكانك', 'place.gps': 'استخدم موقعي', 'place.gpsFail': 'تعذّر تحديد موقعك. اختر مدينة.', 'place.country': 'البلد', 'place.town': 'ابحث عن مدينة أو سوق', 'place.current': 'مكاني',
'rain.title': 'توقعات المطر', 'rain.next': 'الأشهر الثلاثة القادمة', 'rain.drier': 'أجف من المعتاد', 'rain.normal': 'مطر معتاد', 'rain.wetter': 'أرطب من المعتاد',
'rain.dry': 'موسم جاف: قلة المطر أمر معتاد', 'rain.lowConf': 'ثقة منخفضة: قريب من المعتاد', 'rain.someConf': 'ثقة متوسطة', 'rain.usualRain': 'المطر المعتاد', 'rain.chance': 'الاحتمال',
'rain.calendar': 'المطر على مدار السنة', 'rain.last': 'آخر 12 شهرًا', 'rain.vsUsual': 'مقارنةً بالمعتاد', 'rain.noData': 'لا توجد بيانات مطر لهذا المكان.',
'rain.disclaimer': 'توقعات المطر بعيدة المدى غير مؤكدة. استخدمها مع نصيحة مكتب الزراعة.', 'rain.dataTo': 'بيانات المطر حتى',
'settings.title': 'الإعدادات', 'settings.language': 'اللغة', 'settings.about': 'حول', 'settings.aboutText': 'يعمل Agri Lab على هاتفك. صورك لا تغادر هاتفك أبدًا.', 'settings.version': 'الإصدار',
'tab.ask': 'اسأل', 'ask.title': 'اسأل Agri Lab', 'ask.sub': 'اسأل عن أمراض النباتات والأسعار والمطر والتربة', 'ask.placeholder': 'اكتب سؤالك…', 'ask.try': 'جرّب أن تسأل',
'ask.hello': 'مرحبًا! يمكنني الإجابة عن أسئلة حول أمراض النباتات وأسعار المحاصيل والمطر والتربة. ماذا تريد أن تعرف؟',
'ask.q.disease': 'كيف أعالج اللفحة المتأخرة في الطماطم؟', 'ask.q.price': 'كم سيكون سعر الذرة الشهر القادم؟', 'ask.q.rain': 'هل ستمطر هذا الأسبوع؟', 'ask.q.fert': 'أي سماد يجب أن أشتري؟',
'ask.q.rotation': 'ماذا أزرع بعد الذرة؟', 'ask.q.when': 'متى أزرع الفاصولياء؟', 'ask.q.sell': 'أين أبيع الكسافا؟', 'ask.q.help': 'ماذا يستطيع هذا التطبيق أن يفعل؟',
'ask.outOfScope': 'أعرف في Agri Lab فقط أمراض النباتات وأسعار المحاصيل والمطر والتربة، لذلك لا أستطيع الإجابة عن هذا. يمكنك أن تسألني أشياء مثل:',
'ask.notFound': 'ليست لدي معلومات عن ذلك في بياناتي بعد.', 'ask.noPlace': 'اختر مكانك أولًا لأجيب بما يناسب منطقتك.', 'ask.setPlace': 'اختيار مكاني',
'ask.whichCrop': 'أي محصول تقصد؟', 'ask.noPrice': 'ليست لدي بيانات أسعار {crop} في بلدك.', 'ask.priceNow': '{crop}: نحو {price} {cur} {unit} الآن.',
'ask.priceTrend': 'بعد 3 أشهر: {pct} %. أفضل شهر للبيع: {best}.', 'ask.rainDays': 'احتمال المطر: {list}.', 'ask.rainMonth': 'في {month} تمطر نحو {n} أيام.',
'ask.askRain': 'لمزيد من الدقة، أخبرني في تبويب المطر إن كانت قد أمطرت اليوم.', 'ask.soil': 'تربتك: {rich}. {low}', 'ask.richIn': 'غنية بـ{x}', 'ask.lowIn': 'ينقصها {x}.',
'ask.bestCrops': 'أفضل المحاصيل لأرضك: {list}.', 'ask.afterCrop': 'بعد {crop} ازرع: {list}.', 'ask.fertFor': 'لـ{crop} اشترِ: {list}.',
'ask.fertNone': 'تربتك فيها بالفعل ما يحتاجه {crop}. أضف السماد العضوي لتبقى سليمة.', 'ask.plantWhen': 'يبدأ المطر نحو {month}. ازرع {crop} في {month}.',
'ask.sellWhere': 'أفضل أسعار {crop} قربك: {list}.',
'ask.help': 'يمكنني تسمية أمراض النباتات من صورة (فحص)، وإخبارك بما تفعله، وتوقّع أسعار المحاصيل، وعرض احتمالات المطر، وتقديم النصح حول التربة والسماد وما تزرعه (الأرض). اسألني بكلماتك.',
'ask.disclaimer': 'تأتي الإجابات من بيانات التطبيق ونماذجه، وليس من الإنترنت.', 'ask.open': 'فتح', 'ask.you': 'أنت',
'audio.listen': 'استمع', 'audio.stop': 'إيقاف', 'audio.none': 'لا يوجد صوت لهذه اللغة على هذا الهاتف.',
'lang.search': 'ابحث عن لغة', 'lang.group.top': 'مقترحة', 'lang.group.africa': 'أفريقيا', 'lang.group.asia': 'آسيا', 'lang.beta': 'تجريبي', 'lang.more': 'المزيد من اللغات ({n})',
'lang.betaNote': 'اللغات المعلَّمة «تجريبي» مترجمة آليًا ولا يزال متحدثوها الأصليون يراجعونها. في هذه اللغات تبقى نصائح النباتات بالإنجليزية المراجَعة والترجمة على بُعد نقرة.',
'scan.unsupported': 'غير موجود في بياناتنا بعد', 'scan.unsupportedBody': 'يبدو كأنه {crop}، لكن Agri Lab لا يملك نصائح لأمراضه بعد.', 'scan.unsupportedOther': 'يبدو نباتًا، لكنه غير موجود في بياناتنا بعد.',
'scan.unsupportedMore': 'نضيف المزيد من النباتات مع الوقت. اطلب مساعدة المرشد الزراعي بشأن هذا النبات.', 'scan.plant': 'نبات', 'scan.notPlantPct': 'ليس نباتًا', 'scan.bestGuess': 'أفضل تخمين',
'app.name': 'Agri Lab', 'tab.home': 'الرئيسية', 'tab.scan': 'فحص', 'tab.prices': 'الأسعار', 'tab.land': 'الأرض', 'tab.rain': 'المطر',
'greet.morning': 'صباح الخير', 'greet.afternoon': 'مساء الخير', 'greet.evening': 'مساء الخير', 'home.today': 'اليوم', 'home.rainToday': 'احتمال يوم ماطر في {month}', 'home.setPlace': 'اختر مكانك لمعلومات محلية',
'home.land': 'أرضي', 'home.landSub': 'التربة والسماد وأفضل المحاصيل', 'home.install': 'ثبّت Agri Lab', 'home.installSub': 'استخدمه كتطبيق عادي، حتى بدون إنترنت',
'ob.welcome': 'مرحبًا بك في Agri Lab', 'ob.pickLang': 'اختر لغتك', 'ob.1.t': 'افحص ورقة', 'ob.1.d': 'وجّه الكاميرا، اضغط، واعرف المشكلة خلال ثوانٍ.',
'ob.2.t': 'الأسعار والمطر', 'ob.2.d': 'اعرف بكم قد يُباع محصولك ومتى يُتوقع المطر.', 'ob.3.t': 'اعرف أرضك', 'ob.3.d': 'عناصر التربة والسماد المناسب وأفضل المحاصيل لحقلك.',
'ob.4.t': 'يعمل بدون إنترنت', 'ob.4.d': 'لا تحتاج إلى إنترنت بعد التثبيت. صورك لا تغادر هاتفك أبدًا.', 'ob.next': 'متابعة', 'ob.skip': 'تخطّي', 'ob.start': 'ابدأ',
'in.title': 'ثبّت Agri Lab', 'in.sub': 'أضفه إلى الشاشة الرئيسية لتستخدمه كأي تطبيق، حتى بدون إنترنت.', 'in.button': 'تثبيت', 'in.done': 'مثبَّت على هذا الجهاز', 'in.later': 'ليس الآن',
'in.ios.safari.1': 'اضغط على زر المشاركة', 'in.ios.safari.2': 'اختر «إضافة إلى الشاشة الرئيسية»', 'in.ios.safari.3': 'اضغط «إضافة»',
'in.ios.chrome.1': 'اضغط على زر المشاركة بجانب شريط العنوان', 'in.ios.chrome.2': 'اختر «إضافة إلى الشاشة الرئيسية»', 'in.ios.chrome.3': 'اضغط «إضافة»',
'in.ios.other': 'افتح هذه الصفحة في Safari، ثم اضغط مشاركة واختر «إضافة إلى الشاشة الرئيسية».',
'in.and.chrome.1': 'اضغط على قائمة ⋮', 'in.and.chrome.2': 'اختر «تثبيت التطبيق» (أو «إضافة إلى الشاشة الرئيسية»)', 'in.and.chrome.3': 'أكّد',
'in.and.samsung.1': 'اضغط على قائمة ≡', 'in.and.samsung.2': 'اضغط «إضافة الصفحة إلى»', 'in.and.samsung.3': 'اختر «الشاشة الرئيسية»',
'in.and.firefox.1': 'اضغط على قائمة ⋮', 'in.and.firefox.2': 'اختر «تثبيت»', 'in.and.firefox.3': 'أكّد',
'in.desk.chromium.1': 'انقر على أيقونة التثبيت في شريط العنوان', 'in.desk.chromium.2': 'انقر «تثبيت»',
'in.desk.safari.1': 'من شريط القوائم اختر File ▸ Add to Dock', 'in.desk.firefox': 'افتح هذه الصفحة في Chrome أو Edge لتثبيته.',
'in.other': 'افتح قائمة المتصفح واختر «تثبيت» أو «إضافة إلى الشاشة الرئيسية».',
'land.title': 'أرضي', 'land.sub': 'بماذا تتميز تربتك، وماذا تشتري، وماذا تزرع', 'land.noData': 'لا توجد بيانات تربة لهذا الموقع (صحراء أو ماء أو غابة كثيفة). اختر منطقة زراعية قريبة.',
'land.approx': 'تقدير إقليمي (5–25 كم). تحليل التربة أدق.', 'land.soil': 'تربتك', 'land.rich': 'غنية بـ', 'land.low': 'تحتاج إلى المزيد', 'land.balanced': 'لا ينقصها شيء',
'land.k': 'البوتاسيوم', 'land.p': 'الفوسفور', 'land.n': 'النيتروجين', 'land.oc': 'المادة العضوية', 'land.ph': 'الحموضة (pH)', 'land.cec': 'القدرة على حفظ العناصر',
'land.lvl.low': 'منخفض', 'land.lvl.medium': 'متوسط', 'land.lvl.high': 'غني', 'land.ph.acid': 'حمضية', 'land.ph.ok': 'متوازنة', 'land.ph.alkaline': 'قلوية',
'land.texture': 'نوع التربة', 'land.tex.sandy': 'رملية', 'land.tex.loam': 'طميية', 'land.tex.clayey': 'طينية', 'land.climate': 'المناخ', 'land.temp': 'متوسط الحرارة', 'land.rain': 'المطر في السنة',
'land.last': 'ماذا زرعت في الموسم الماضي؟', 'land.lastNone': 'لا شيء / لست متأكدًا', 'land.best': 'أفضل المحاصيل لأرضك', 'land.pickCrop': 'اضغط على محصول لترى السماد الذي يحتاجه',
'land.why.legume_after': 'البقوليات تعيد النيتروجين إلى التربة.', 'land.why.same_crop': 'تكرار المحصول نفسه يزيد الآفات والأمراض.', 'land.why.same_family': 'النباتات من العائلة نفسها تشترك في الآفات والأمراض.',
'land.why.cereal_after_legume': 'الحبوب تنمو جيدًا بعد البقوليات.', 'land.why.root_after_legume': 'محاصيل الجذور تستفيد من النيتروجين الذي تتركه البقوليات.',
'land.fert': 'السماد الذي تشتريه', 'land.fertNone': 'تربتك فيها بالفعل ما يكفي مما يحتاجه هذا المحصول. أضف السماد العضوي لتبقى سليمة.',
'land.prod.urea': 'يوريا (نيتروجين)', 'land.prod.dap': 'DAP (فوسفور)', 'land.prod.mop': 'MOP / بوتاس (بوتاسيوم)', 'land.prod.lime': 'جير زراعي (يقلل الحموضة)', 'land.prod.compost': 'سماد عضوي أو روث',
'land.rate': 'نحو {a}–{b} كغ للهكتار', 'land.fertNote': 'كميات استرشادية. تأكد من المرشد الزراعي أو بتحليل التربة.', 'land.source': 'مبني على خرائط التربة بالأقمار الصناعية (iSDAsoil) وWorldClim وأمطار CHIRPS.',
'rain.days': 'أيام', 'rain.months': 'أشهر', 'rain.chances': 'احتمالات المطر', 'rain.didRain': 'هل أمطرت اليوم؟', 'rain.yesterday': 'وأمس؟', 'rain.yes': 'نعم', 'rain.no': 'لا',
'rain.next7': 'الأيام السبعة القادمة', 'rain.today': 'اليوم', 'rain.tomorrow': 'غدًا', 'rain.typical': 'هذا الشهر: نحو {n} أيام ماطرة', 'rain.heavy': 'اليوم الماطر يجلب نحو {mm} مم',
'rain.tipDry': 'أفضل الأيام للرش أو الحصاد', 'rain.tipWet': 'أفضل الأيام للزراعة أو التسميد', 'rain.offlineNote': 'تقدير دون اتصال مبني على أنماط المطر السابقة. حدّث الإجابتين كل يوم.',
'settings.theme': 'المظهر', 'theme.auto': 'تلقائي', 'theme.light': 'فاتح', 'theme.dark': 'داكن', 'settings.install': 'التثبيت على هذا الجهاز',
'ask.thanks': 'على الرحب والسعة!',
'ask.advEnglish': 'تُعرض نصائح النباتات بالإنجليزية المراجَعة لهذه اللغة (تجريبي).',
'ask.chooseProblem': 'أي مشكلة تقصد؟',
'ask.scanHint': 'أخبرني بالمحصول والمشكلة، أو افحص ورقة.',
'ask.sellHead': 'أفضل أسعار {crop} قربك:',
'ask.fertHead': 'لـ{crop} اشترِ:',
'ask.send': 'إرسال',
'audio.pack': 'الصوت (استماع)',
'audio.ready': 'جاهز دون اتصال',
'audio.download': 'تنزيل',
'audio.downloading': 'جارٍ التنزيل…',
'audio.deviceVoice': 'يستخدم صوت الهاتف',
'audio.noneSettings': 'غير متاح',
}
