"""Español (hand-written)."""
UI = {
'tagline': "Tu ayudante del campo. Funciona sin internet tras el primer uso con conexión.", 'chooseLang': 'Elige tu idioma', 'start': 'Empezar', 'back': 'Atrás', 'close': 'Cerrar', 'loading': 'Cargando…',
'error': 'Algo salió mal. Inténtalo de nuevo.',
'home.scan': 'Revisar mi planta', 'home.scanSub': 'Haz una foto de una hoja', 'home.prices': 'Precios de cultivos', 'home.pricesSub': '¿A cuánto se venderá mi cosecha?',
'home.rain': 'Pronóstico de lluvia', 'home.rainSub': '¿Lloverá en los próximos meses?', 'home.settings': 'Ajustes', 'home.offlineReady': 'Listo: funciona sin internet', 'home.offlinePrep': "Guardando datos para usar sin conexión… mantén internet hasta terminar",
'scan.title': 'Revisar mi planta', 'scan.mt': 'Ver traducción automática (sin revisar)', 'scan.which': '¿Qué plantas puedo revisar?', 'scan.tip1': 'Pon una sola hoja en el centro', 'scan.tip2': 'Usa luz del día',
'scan.tip3': 'Sujeta bien el teléfono', 'scan.take': 'Hacer una foto', 'scan.gallery': 'Elegir una foto', 'scan.loading': 'Mirando tu planta…', 'scan.firstTime': 'Preparando (solo la primera vez)…',
'scan.retake': 'Hacer otra foto', 'scan.notPlant': 'Esto no es una hoja de planta', 'scan.unsure': 'No estoy seguro', 'scan.crop': 'Planta', 'scan.healthy': 'Sana', 'scan.sick': 'Necesita atención',
'scan.sure.high': 'Muy seguro', 'scan.sure.mid': 'Bastante seguro', 'scan.sure.low': 'Poco seguro', 'scan.maybe': 'También podría ser', 'scan.what': '¿Qué es?', 'scan.treat': 'Qué hacer',
'scan.prevent': 'Cómo prevenirlo', 'scan.machine': 'Traducido por ordenador. Consulta a un experto agrícola.', 'scan.noModel': 'El modelo de plantas no está instalado en esta versión.',
'price.title': 'Precios de cultivos', 'price.in3m': 'en 3 meses', 'price.expected': 'Esperado', 'price.place': 'Mi lugar', 'price.crop': 'Elige un cultivo', 'price.search': 'Buscar un cultivo',
'price.now': 'Precio ahora', 'price.perKg': 'por kg', 'price.perL': 'por litro', 'price.next': 'Precio esperado en los próximos meses', 'price.range': 'Rango probable', 'price.up': 'El precio probablemente subirá',
'price.down': 'El precio probablemente bajará', 'price.flat': 'El precio probablemente se mantendrá', 'price.best': 'Mejor mes para vender', 'price.where': 'Dónde vender cerca', 'price.km': 'km',
'price.updated': 'Precio de', 'price.currency': 'Mostrar precios en', 'price.err': 'Los pronósticos pasados fallaban en unos', 'price.noData': 'Aún no hay precios para este país.',
'price.setPlace': 'Primero elige tu lugar', 'price.buyers': 'Quién compra de tu país', 'price.prod': 'Valor de la producción en 5 años',
'price.disclaimer': 'Un pronóstico es una estimación basada en precios pasados. Consulta el mercado antes de vender.',
'place.title': 'Elige tu lugar', 'place.gps': 'Usar mi ubicación', 'place.gpsFail': 'No se pudo obtener tu ubicación. Elige una ciudad.', 'place.country': 'País', 'place.town': 'Buscar ciudad o mercado', 'place.current': 'Mi lugar',
'rain.title': 'Pronóstico de lluvia', 'rain.next': 'Próximos 3 meses', 'rain.drier': 'Más seco de lo normal', 'rain.normal': 'Lluvia normal', 'rain.wetter': 'Más húmedo de lo normal',
'rain.dry': 'Estación seca: es normal que llueva poco', 'rain.lowConf': 'Poca confianza: cercano a lo normal', 'rain.someConf': 'Confianza media', 'rain.usualRain': 'Lluvia habitual', 'rain.chance': 'Probabilidad',
'rain.calendar': 'La lluvia durante el año', 'rain.last': 'Últimos 12 meses', 'rain.vsUsual': 'comparado con lo habitual', 'rain.noData': 'No hay datos de lluvia para este lugar.',
'rain.disclaimer': 'Los pronósticos de lluvia a largo plazo son inciertos. Úsalos junto con el consejo de tu oficina agraria.', 'rain.dataTo': 'Datos de lluvia hasta',
'settings.title': 'Ajustes', 'settings.language': 'Idioma', 'settings.about': 'Acerca de', 'settings.aboutText': 'Agri Lab funciona en tu teléfono. Tus fotos nunca salen de él.', 'settings.version': 'Versión',
'tab.ask': 'Preguntar', 'ask.title': 'Pregunta a Agri Lab', 'ask.sub': 'Pregunta sobre enfermedades de plantas, precios, lluvia y suelo', 'ask.placeholder': 'Escribe tu pregunta…', 'ask.try': 'Prueba a preguntar',
'ask.hello': '¡Hola! Puedo responder preguntas sobre enfermedades de plantas, precios de cultivos, lluvia y suelo. ¿Qué quieres saber?',
'ask.q.disease': '¿Cómo trato el tizón tardío del tomate?', 'ask.q.price': '¿Cuánto costará el maíz el mes que viene?', 'ask.q.rain': '¿Lloverá esta semana?', 'ask.q.fert': '¿Qué fertilizante debo comprar?',
'ask.q.rotation': '¿Qué debo sembrar después del maíz?', 'ask.q.when': '¿Cuándo debo sembrar frijoles?', 'ask.q.sell': '¿Dónde puedo vender yuca?', 'ask.q.help': '¿Qué puede hacer esta aplicación?',
'ask.outOfScope': 'En Agri Lab solo conozco enfermedades de plantas, precios de cultivos, lluvia y suelo, así que no puedo responder eso. Puedes preguntarme cosas como:',
'ask.notFound': 'Todavía no tengo información sobre eso en mis datos.', 'ask.noPlace': 'Elige primero tu lugar para que pueda responder para tu zona.', 'ask.setPlace': 'Elegir mi lugar',
'ask.whichCrop': '¿A qué cultivo te refieres?', 'ask.noPrice': 'No tengo precios de {crop} en tu país.', 'ask.priceNow': '{crop}: unos {price} {cur} {unit} ahora.',
'ask.priceTrend': 'En 3 meses: {pct} %. Mejor mes para vender: {best}.', 'ask.rainDays': 'Probabilidad de lluvia: {list}.', 'ask.rainMonth': 'En {month} llueve unos {n} días.',
'ask.askRain': 'Para más precisión, dime en la pestaña Lluvia si hoy llovió.', 'ask.soil': 'Tu suelo: {rich}. {low}', 'ask.richIn': 'rico en {x}', 'ask.lowIn': 'Falta {x}.',
'ask.bestCrops': 'Mejores cultivos para tu tierra: {list}.', 'ask.afterCrop': 'Después de {crop}, siembra: {list}.', 'ask.fertFor': 'Para {crop} compra: {list}.',
'ask.fertNone': 'Tu suelo ya tiene lo que necesita {crop}. Añade compost para mantenerlo sano.', 'ask.plantWhen': 'La lluvia empieza hacia {month}. Siembra {crop} en {month}.',
'ask.sellWhere': 'Mejores precios de {crop} cerca de ti: {list}.',
'ask.help': 'Puedo nombrar enfermedades de plantas a partir de una foto (Escanear), decirte qué hacer, prever precios, mostrar probabilidades de lluvia y aconsejar sobre suelo, fertilizante y qué sembrar (Tierra). Pregúntame con tus palabras.',
'ask.disclaimer': 'Las respuestas salen de los datos y modelos de la aplicación, no de internet.', 'ask.open': 'Abrir', 'ask.you': 'Tú',
'audio.listen': 'Escuchar', 'audio.stop': 'Parar', 'audio.none': 'No hay voz para este idioma en este teléfono.',
'lang.search': 'Buscar idioma', 'lang.group.top': 'Sugeridos', 'lang.group.africa': 'África', 'lang.group.asia': 'Asia', 'lang.beta': 'beta', 'lang.more': 'Más idiomas ({n})',
'lang.betaNote': 'Los idiomas «beta» están traducidos automáticamente y aún los revisan hablantes nativos. En ellos, los consejos se muestran en inglés revisado y la traducción está a un toque.',
'scan.unsupported': 'Aún no está en nuestros datos', 'scan.unsupportedBody': 'Parece {crop}, pero Agri Lab aún no tiene consejos de enfermedades para esta planta.', 'scan.unsupportedOther': 'Parece una planta, pero aún no está en nuestros datos.',
'scan.unsupportedMore': 'Vamos añadiendo más plantas con el tiempo. Pide ayuda a tu técnico agrícola para esta.', 'scan.plant': 'Planta', 'scan.notPlantPct': 'No es una planta', 'scan.bestGuess': 'Mejor suposición',
'app.name': 'Agri Lab', 'tab.home': 'Inicio', 'tab.scan': 'Escanear', 'tab.prices': 'Precios', 'tab.land': 'Tierra', 'tab.rain': 'Lluvia',
'greet.morning': 'Buenos días', 'greet.afternoon': 'Buenas tardes', 'greet.evening': 'Buenas noches', 'home.today': 'Hoy', 'home.rainToday': 'Probabilidad de un día de lluvia en {month}', 'home.setPlace': 'Elige tu lugar para ver datos locales',
'home.land': 'Mi tierra', 'home.landSub': 'Suelo, fertilizante y mejores cultivos', 'home.install': 'Instalar Agri Lab', 'home.installSub': "Úsala como una app normal. Ábrela una vez con internet y luego funciona sin conexión",
'ob.welcome': 'Bienvenido a Agri Lab', 'ob.pickLang': 'Elige tu idioma', 'ob.1.t': 'Escanea una hoja', 'ob.1.d': 'Apunta, toca y descubre qué le pasa en segundos.',
'ob.2.t': 'Precios y lluvia', 'ob.2.d': 'Mira a cuánto puede venderse tu cosecha y cuándo es probable que llueva.', 'ob.3.t': 'Conoce tu tierra', 'ob.3.d': 'Nutrientes del suelo, el fertilizante adecuado y los mejores cultivos para tu campo.',
'ob.4.t': 'Funciona sin conexión', 'ob.4.d': "Ábrela una primera vez con internet para guardarlo todo. Después funciona sin internet. Tus fotos nunca salen de tu teléfono.", 'ob.next': 'Continuar', 'ob.skip': 'Omitir', 'ob.start': 'Empezar',
'in.title': 'Instalar Agri Lab', 'in.sub': "Añádela a tu pantalla de inicio. Ábrela una primera vez con internet para guardarlo todo; después funciona sin conexión.", 'in.button': 'Instalar', 'in.done': 'Instalada en este dispositivo', 'in.later': 'Ahora no',
'in.ios.safari.1': 'Toca el botón Compartir', 'in.ios.safari.2': 'Elige «Añadir a pantalla de inicio»', 'in.ios.safari.3': 'Toca «Añadir»',
'in.ios.chrome.1': 'Toca el botón Compartir junto a la barra de direcciones', 'in.ios.chrome.2': 'Elige «Añadir a pantalla de inicio»', 'in.ios.chrome.3': 'Toca «Añadir»',
'in.ios.other': 'Abre esta página en Safari, toca Compartir y elige «Añadir a pantalla de inicio».',
'in.and.chrome.1': 'Toca el menú ⋮', 'in.and.chrome.2': 'Elige «Instalar aplicación» (o «Añadir a la pantalla de inicio»)', 'in.and.chrome.3': 'Confirma',
'in.and.samsung.1': 'Toca el menú ≡', 'in.and.samsung.2': 'Toca «Añadir página a»', 'in.and.samsung.3': 'Elige «Pantalla de inicio»',
'in.and.firefox.1': 'Toca el menú ⋮', 'in.and.firefox.2': 'Elige «Instalar»', 'in.and.firefox.3': 'Confirma',
'in.desk.chromium.1': 'Haz clic en el icono de instalar de la barra de direcciones', 'in.desk.chromium.2': 'Haz clic en «Instalar»',
'in.desk.safari.1': 'En la barra de menús elige Archivo ▸ Añadir al Dock', 'in.desk.firefox': 'Abre esta página en Chrome o Edge para instalarla.',
'in.other': 'Abre el menú del navegador y elige «Instalar» o «Añadir a la pantalla de inicio».',
'land.title': 'Mi tierra', 'land.sub': 'De qué es rico tu suelo, qué comprar y qué sembrar', 'land.noData': 'No hay datos de suelo aquí (desierto, agua o selva densa). Elige una zona agrícola cercana.',
'land.approx': 'Estimación regional (5–25 km). Un análisis de suelo es más exacto.', 'land.soil': 'Tu suelo', 'land.rich': 'Rico en', 'land.low': 'Necesita más', 'land.balanced': 'No falta nada',
'land.k': 'Potasio', 'land.p': 'Fósforo', 'land.n': 'Nitrógeno', 'land.oc': 'Materia orgánica', 'land.ph': 'Acidez (pH)', 'land.cec': 'Retención de nutrientes',
'land.lvl.low': 'Bajo', 'land.lvl.medium': 'Medio', 'land.lvl.high': 'Rico', 'land.ph.acid': 'Ácido', 'land.ph.ok': 'Equilibrado', 'land.ph.alkaline': 'Alcalino',
'land.texture': 'Tipo de suelo', 'land.tex.sandy': 'Arenoso', 'land.tex.loam': 'Franco', 'land.tex.clayey': 'Arcilloso', 'land.climate': 'Clima', 'land.temp': 'Temperatura media', 'land.rain': 'Lluvia al año',
'land.last': '¿Qué cultivaste la temporada pasada?', 'land.lastNone': 'Nada / no sé', 'land.best': 'Mejores cultivos para tu tierra', 'land.pickCrop': 'Toca un cultivo para ver qué fertilizante necesita',
'land.why.legume_after': 'Las leguminosas devuelven nitrógeno al suelo.', 'land.why.same_crop': 'Repetir el mismo cultivo acumula plagas y enfermedades.', 'land.why.same_family': 'La misma familia de plantas comparte plagas y enfermedades.',
'land.why.cereal_after_legume': 'Los cereales crecen bien después de las leguminosas.', 'land.why.root_after_legume': 'Las raíces aprovechan el nitrógeno que dejan las leguminosas.',
'land.fert': 'Fertilizante para comprar', 'land.fertNone': 'Tu suelo ya tiene lo suficiente de lo que este cultivo necesita. Añade compost para mantenerlo sano.',
'land.prod.urea': 'Urea (nitrógeno)', 'land.prod.dap': 'DAP (fósforo)', 'land.prod.mop': 'MOP / potasa (potasio)', 'land.prod.lime': 'Cal agrícola (reduce la acidez)', 'land.prod.compost': 'Compost o estiércol',
'land.rate': 'unos {a}–{b} kg por hectárea', 'land.fertNote': 'Cantidades orientativas. Confírmalas con tu técnico agrícola o con un análisis de suelo.', 'land.source': 'Basado en mapas de suelo por satélite (iSDAsoil), WorldClim y lluvias CHIRPS.',
'rain.days': 'Días', 'rain.months': 'Meses', 'rain.chances': 'Probabilidad de lluvia', 'rain.didRain': '¿Llovió hoy?', 'rain.yesterday': '¿Y ayer?', 'rain.yes': 'Sí', 'rain.no': 'No',
'rain.next7': 'Próximos 7 días', 'rain.today': 'Hoy', 'rain.tomorrow': 'Mañana', 'rain.typical': 'Este mes: unos {n} días de lluvia', 'rain.heavy': 'Un día de lluvia trae unos {mm} mm',
'rain.tipDry': 'Mejores días para fumigar o cosechar', 'rain.tipWet': 'Mejores días para sembrar o fertilizar', 'rain.offlineNote': 'Estimación sin conexión según patrones de lluvia pasados. Actualiza las dos respuestas cada día.',
'settings.theme': 'Apariencia', 'theme.auto': 'Auto', 'theme.light': 'Claro', 'theme.dark': 'Oscuro', 'settings.install': 'Instalar en este dispositivo',
'ask.thanks': '¡De nada!',
'ask.advEnglish': 'Los consejos sobre plantas se muestran en inglés revisado para este idioma (beta).',
'ask.chooseProblem': '¿A qué problema te refieres?',
'ask.scanHint': 'Dime el cultivo y el problema, o escanea una hoja.',
'ask.sellHead': 'Mejores precios de {crop} cerca de ti:',
'ask.fertHead': 'Para {crop} compra:',
'ask.send': 'Enviar',
'audio.pack': 'Voz (escuchar)',
'audio.ready': 'Lista sin conexión',
'audio.download': 'Descargar',
'audio.downloading': 'Descargando…',
'audio.deviceVoice': 'Usa la voz del teléfono',
'audio.noneSettings': 'No disponible',
}
