"""Português (hand-written; neutral between Brazil and Mozambique/Angola)."""
UI = {
'tagline': 'O seu ajudante no campo. Funciona sem internet.', 'chooseLang': 'Escolha o seu idioma', 'start': 'Começar', 'back': 'Voltar', 'close': 'Fechar', 'loading': 'A carregar…',
'error': 'Algo correu mal. Tente novamente.',
'home.scan': 'Verificar a minha planta', 'home.scanSub': 'Tire uma foto de uma folha', 'home.prices': 'Preços das culturas', 'home.pricesSub': 'Por quanto vou vender a minha colheita?',
'home.rain': 'Previsão de chuva', 'home.rainSub': 'Os próximos meses serão chuvosos?', 'home.settings': 'Definições', 'home.offlineReady': 'Pronto: funciona sem internet', 'home.offlinePrep': 'A guardar dados para uso offline…',
'scan.title': 'Verificar a minha planta', 'scan.mt': 'Ver tradução automática (não revista)', 'scan.which': 'Que plantas posso verificar?', 'scan.tip1': 'Coloque uma só folha ao centro', 'scan.tip2': 'Use luz do dia',
'scan.tip3': 'Segure bem o telemóvel', 'scan.take': 'Tirar uma foto', 'scan.gallery': 'Escolher uma foto', 'scan.loading': 'A analisar a sua planta…', 'scan.firstTime': 'A preparar (só na primeira vez)…',
'scan.retake': 'Tirar outra foto', 'scan.notPlant': 'Isto não é uma folha de planta', 'scan.unsure': 'Não tenho certeza', 'scan.crop': 'Planta', 'scan.healthy': 'Saudável', 'scan.sick': 'Precisa de atenção',
'scan.sure.high': 'Muito seguro', 'scan.sure.mid': 'Bastante seguro', 'scan.sure.low': 'Pouco seguro', 'scan.maybe': 'Também pode ser', 'scan.what': 'O que é?', 'scan.treat': 'O que fazer',
'scan.prevent': 'Como prevenir', 'scan.machine': 'Traduzido por computador. Consulte um especialista agrícola.', 'scan.noModel': 'O modelo de plantas não está instalado nesta versão.',
'price.title': 'Preços das culturas', 'price.in3m': 'em 3 meses', 'price.expected': 'Esperado', 'price.place': 'O meu local', 'price.crop': 'Escolha uma cultura', 'price.search': 'Procurar uma cultura',
'price.now': 'Preço agora', 'price.perKg': 'por kg', 'price.perL': 'por litro', 'price.next': 'Preço esperado nos próximos meses', 'price.range': 'Intervalo provável', 'price.up': 'O preço deve subir',
'price.down': 'O preço deve descer', 'price.flat': 'O preço deve manter-se', 'price.best': 'Melhor mês para vender', 'price.where': 'Onde vender perto', 'price.km': 'km',
'price.updated': 'Preço de', 'price.currency': 'Mostrar preços em', 'price.err': 'As previsões passadas falhavam cerca de', 'price.noData': 'Ainda não há preços para este país.',
'price.setPlace': 'Escolha primeiro o seu local', 'price.buyers': 'Quem compra do seu país', 'price.prod': 'Valor da produção em 5 anos',
'price.disclaimer': 'Uma previsão é uma estimativa baseada em preços passados. Confirme no mercado antes de vender.',
'place.title': 'Escolha o seu local', 'place.gps': 'Usar a minha localização', 'place.gpsFail': 'Não foi possível obter a localização. Escolha uma cidade.', 'place.country': 'País', 'place.town': 'Procurar cidade ou mercado', 'place.current': 'O meu local',
'rain.title': 'Previsão de chuva', 'rain.next': 'Próximos 3 meses', 'rain.drier': 'Mais seco que o normal', 'rain.normal': 'Chuva normal', 'rain.wetter': 'Mais húmido que o normal',
'rain.dry': 'Estação seca: é normal chover pouco', 'rain.lowConf': 'Pouca confiança: próximo do normal', 'rain.someConf': 'Confiança média', 'rain.usualRain': 'Chuva habitual', 'rain.chance': 'Probabilidade',
'rain.calendar': 'A chuva ao longo do ano', 'rain.last': 'Últimos 12 meses', 'rain.vsUsual': 'em comparação com o habitual', 'rain.noData': 'Não há dados de chuva para este local.',
'rain.disclaimer': 'As previsões de chuva a longo prazo são incertas. Use-as com o conselho do seu serviço agrário.', 'rain.dataTo': 'Dados de chuva até',
'settings.title': 'Definições', 'settings.language': 'Idioma', 'settings.about': 'Acerca de', 'settings.aboutText': 'O Agri Lab funciona no seu telemóvel. As suas fotos nunca saem dele.', 'settings.version': 'Versão',
'tab.ask': 'Perguntar', 'ask.title': 'Pergunte ao Agri Lab', 'ask.sub': 'Pergunte sobre doenças de plantas, preços, chuva e solo', 'ask.placeholder': 'Escreva a sua pergunta…', 'ask.try': 'Experimente perguntar',
'ask.hello': 'Olá! Posso responder a perguntas sobre doenças de plantas, preços de culturas, chuva e solo. O que quer saber?',
'ask.q.disease': 'Como trato o míldio do tomateiro?', 'ask.q.price': 'Quanto vai custar o milho no próximo mês?', 'ask.q.rain': 'Vai chover esta semana?', 'ask.q.fert': 'Que adubo devo comprar?',
'ask.q.rotation': 'O que devo plantar depois do milho?', 'ask.q.when': 'Quando devo plantar feijão?', 'ask.q.sell': 'Onde posso vender mandioca?', 'ask.q.help': 'O que faz esta aplicação?',
'ask.outOfScope': 'No Agri Lab só conheço doenças de plantas, preços de culturas, chuva e solo, por isso não posso responder a isso. Pode perguntar-me coisas como:',
'ask.notFound': 'Ainda não tenho informação sobre isso nos meus dados.', 'ask.noPlace': 'Escolha primeiro o seu local para eu responder para a sua zona.', 'ask.setPlace': 'Escolher o meu local',
'ask.whichCrop': 'A que cultura se refere?', 'ask.noPrice': 'Não tenho preços de {crop} no seu país.', 'ask.priceNow': '{crop}: cerca de {price} {cur} {unit} agora.',
'ask.priceTrend': 'Daqui a 3 meses: {pct} %. Melhor mês para vender: {best}.', 'ask.rainDays': 'Probabilidade de chuva: {list}.', 'ask.rainMonth': 'Em {month} chove cerca de {n} dias.',
'ask.askRain': 'Para ser mais preciso, diga-me no separador Chuva se hoje choveu.', 'ask.soil': 'O seu solo: {rich}. {low}', 'ask.richIn': 'rico em {x}', 'ask.lowIn': 'Falta {x}.',
'ask.bestCrops': 'Melhores culturas para a sua terra: {list}.', 'ask.afterCrop': 'Depois de {crop}, plante: {list}.', 'ask.fertFor': 'Para {crop} compre: {list}.',
'ask.fertNone': 'O seu solo já tem o que {crop} precisa. Junte composto para o manter saudável.', 'ask.plantWhen': 'A chuva começa por volta de {month}. Plante {crop} em {month}.',
'ask.sellWhere': 'Melhores preços de {crop} perto de si: {list}.',
'ask.help': 'Posso identificar doenças de plantas a partir de uma foto (Digitalizar), dizer o que fazer, prever preços, mostrar probabilidades de chuva e aconselhar sobre solo, adubo e o que plantar (Terra). Pergunte com as suas palavras.',
'ask.disclaimer': 'As respostas vêm dos dados e modelos da aplicação, não da internet.', 'ask.open': 'Abrir', 'ask.you': 'Você',
'audio.listen': 'Ouvir', 'audio.stop': 'Parar', 'audio.none': 'Não há voz para este idioma neste telemóvel.',
'lang.search': 'Procurar idioma', 'lang.group.top': 'Sugeridos', 'lang.group.africa': 'África', 'lang.group.asia': 'Ásia', 'lang.beta': 'beta', 'lang.more': 'Mais idiomas ({n})',
'lang.betaNote': 'Os idiomas «beta» são traduzidos por máquina e ainda estão a ser revistos por falantes nativos. Neles, os conselhos aparecem em inglês revisto, com a tradução a um toque.',
'scan.unsupported': 'Ainda não está nos nossos dados', 'scan.unsupportedBody': 'Parece {crop}, mas o Agri Lab ainda não tem conselhos de doenças para esta planta.', 'scan.unsupportedOther': 'Parece uma planta, mas ainda não está nos nossos dados.',
'scan.unsupportedMore': 'Vamos acrescentando mais plantas. Peça ajuda ao seu técnico agrícola para esta.', 'scan.plant': 'Planta', 'scan.notPlantPct': 'Não é uma planta', 'scan.bestGuess': 'Melhor palpite',
'app.name': 'Agri Lab', 'tab.home': 'Início', 'tab.scan': 'Digitalizar', 'tab.prices': 'Preços', 'tab.land': 'Terra', 'tab.rain': 'Chuva',
'greet.morning': 'Bom dia', 'greet.afternoon': 'Boa tarde', 'greet.evening': 'Boa noite', 'home.today': 'Hoje', 'home.rainToday': 'Probabilidade de um dia de chuva em {month}', 'home.setPlace': 'Escolha o seu local para ver dados locais',
'home.land': 'A minha terra', 'home.landSub': 'Solo, adubo e melhores culturas', 'home.install': 'Instalar o Agri Lab', 'home.installSub': 'Use como uma app normal, mesmo sem internet',
'ob.welcome': 'Bem-vindo ao Agri Lab', 'ob.pickLang': 'Escolha o seu idioma', 'ob.1.t': 'Digitalize uma folha', 'ob.1.d': 'Aponte, toque e descubra o que se passa em segundos.',
'ob.2.t': 'Preços e chuva', 'ob.2.d': 'Veja por quanto pode vender a colheita e quando é provável que chova.', 'ob.3.t': 'Conheça a sua terra', 'ob.3.d': 'Nutrientes do solo, o adubo certo e as melhores culturas para o seu campo.',
'ob.4.t': 'Funciona offline', 'ob.4.d': 'Não precisa de internet depois de instalar. As suas fotos nunca saem do telemóvel.', 'ob.next': 'Continuar', 'ob.skip': 'Saltar', 'ob.start': 'Começar',
'in.title': 'Instalar o Agri Lab', 'in.sub': 'Adicione-o ao ecrã principal para usar como qualquer app, mesmo sem internet.', 'in.button': 'Instalar', 'in.done': 'Instalado neste dispositivo', 'in.later': 'Agora não',
'in.ios.safari.1': 'Toque no botão Partilhar', 'in.ios.safari.2': 'Escolha «Adicionar ao ecrã principal»', 'in.ios.safari.3': 'Toque em «Adicionar»',
'in.ios.chrome.1': 'Toque no botão Partilhar junto à barra de endereço', 'in.ios.chrome.2': 'Escolha «Adicionar ao ecrã principal»', 'in.ios.chrome.3': 'Toque em «Adicionar»',
'in.ios.other': 'Abra esta página no Safari, toque em Partilhar e escolha «Adicionar ao ecrã principal».',
'in.and.chrome.1': 'Toque no menu ⋮', 'in.and.chrome.2': 'Escolha «Instalar app» (ou «Adicionar ao ecrã principal»)', 'in.and.chrome.3': 'Confirme',
'in.and.samsung.1': 'Toque no menu ≡', 'in.and.samsung.2': 'Toque em «Adicionar página a»', 'in.and.samsung.3': 'Escolha «Ecrã principal»',
'in.and.firefox.1': 'Toque no menu ⋮', 'in.and.firefox.2': 'Escolha «Instalar»', 'in.and.firefox.3': 'Confirme',
'in.desk.chromium.1': 'Clique no ícone de instalar na barra de endereço', 'in.desk.chromium.2': 'Clique em «Instalar»',
'in.desk.safari.1': 'Na barra de menus escolha Ficheiro ▸ Adicionar ao Dock', 'in.desk.firefox': 'Abra esta página no Chrome ou no Edge para a instalar.',
'in.other': 'Abra o menu do navegador e escolha «Instalar» ou «Adicionar ao ecrã principal».',
'land.title': 'A minha terra', 'land.sub': 'Em que o seu solo é rico, o que comprar e o que plantar', 'land.noData': 'Não há dados de solo aqui (deserto, água ou floresta densa). Escolha uma zona agrícola próxima.',
'land.approx': 'Estimativa regional (5–25 km). Uma análise de solo é mais exata.', 'land.soil': 'O seu solo', 'land.rich': 'Rico em', 'land.low': 'Precisa de mais', 'land.balanced': 'Nada em falta',
'land.k': 'Potássio', 'land.p': 'Fósforo', 'land.n': 'Azoto', 'land.oc': 'Matéria orgânica', 'land.ph': 'Acidez (pH)', 'land.cec': 'Retenção de nutrientes',
'land.lvl.low': 'Baixo', 'land.lvl.medium': 'Médio', 'land.lvl.high': 'Rico', 'land.ph.acid': 'Ácido', 'land.ph.ok': 'Equilibrado', 'land.ph.alkaline': 'Alcalino',
'land.texture': 'Tipo de solo', 'land.tex.sandy': 'Arenoso', 'land.tex.loam': 'Franco', 'land.tex.clayey': 'Argiloso', 'land.climate': 'Clima', 'land.temp': 'Temperatura média', 'land.rain': 'Chuva por ano',
'land.last': 'O que cultivou na época passada?', 'land.lastNone': 'Nada / não sei', 'land.best': 'Melhores culturas para a sua terra', 'land.pickCrop': 'Toque numa cultura para ver o adubo de que precisa',
'land.why.legume_after': 'As leguminosas devolvem azoto ao solo.', 'land.why.same_crop': 'Repetir a mesma cultura acumula pragas e doenças.', 'land.why.same_family': 'A mesma família de plantas partilha pragas e doenças.',
'land.why.cereal_after_legume': 'Os cereais crescem bem depois das leguminosas.', 'land.why.root_after_legume': 'As raízes aproveitam o azoto deixado pelas leguminosas.',
'land.fert': 'Adubo a comprar', 'land.fertNone': 'O seu solo já tem o suficiente do que esta cultura precisa. Junte composto para o manter saudável.',
'land.prod.urea': 'Ureia (azoto)', 'land.prod.dap': 'DAP (fósforo)', 'land.prod.mop': 'MOP / potassa (potássio)', 'land.prod.lime': 'Calcário agrícola (reduz a acidez)', 'land.prod.compost': 'Composto ou estrume',
'land.rate': 'cerca de {a}–{b} kg por hectare', 'land.fertNote': 'Quantidades indicativas. Confirme com o seu técnico agrícola ou com uma análise de solo.', 'land.source': 'Com base em mapas de solo por satélite (iSDAsoil), WorldClim e chuva CHIRPS.',
'rain.days': 'Dias', 'rain.months': 'Meses', 'rain.chances': 'Probabilidade de chuva', 'rain.didRain': 'Choveu hoje?', 'rain.yesterday': 'E ontem?', 'rain.yes': 'Sim', 'rain.no': 'Não',
'rain.next7': 'Próximos 7 dias', 'rain.today': 'Hoje', 'rain.tomorrow': 'Amanhã', 'rain.typical': 'Este mês: cerca de {n} dias de chuva', 'rain.heavy': 'Um dia de chuva traz cerca de {mm} mm',
'rain.tipDry': 'Melhores dias para pulverizar ou colher', 'rain.tipWet': 'Melhores dias para plantar ou adubar', 'rain.offlineNote': 'Estimativa offline com base em padrões de chuva passados. Atualize as duas respostas todos os dias.',
'settings.theme': 'Aparência', 'theme.auto': 'Auto', 'theme.light': 'Claro', 'theme.dark': 'Escuro', 'settings.install': 'Instalar neste dispositivo',
'ask.thanks': 'De nada!',
'ask.advEnglish': 'Os conselhos sobre plantas são mostrados em inglês revisto para este idioma (beta).',
'ask.chooseProblem': 'A que problema se refere?',
'ask.scanHint': 'Diga-me a cultura e o problema, ou digitalize uma folha.',
'ask.sellHead': 'Melhores preços de {crop} perto de si:',
'ask.fertHead': 'Para {crop} compre:',
'ask.send': 'Enviar',
'audio.pack': 'Voz (ouvir)',
'audio.ready': 'Pronta offline',
'audio.download': 'Transferir',
'audio.downloading': 'A transferir…',
'audio.deviceVoice': 'Usa a voz do telemóvel',
'audio.noneSettings': 'Indisponível',
}
