"""Validate the hand-written UI dictionaries (scripts/human/ui_<lang>.py) against the English source and emit app/src/i18n/human.ts.

Checks per language: every English key present, no unknown keys, identical {placeholders}.
Usage: python scripts/build_human_ui.py       (needs artifacts/ui_en.json → run `node app/scripts/export-i18n.mjs` first)
"""
import importlib.util
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
EN = json.load(open(ROOT / "artifacts" / "ui_en.json", encoding="utf-8"))
PH = re.compile(r"\{(\w+)\}")
out, bad = {}, 0
for f in sorted((ROOT / "scripts" / "human").glob("ui_*.py")):
    code = f.stem[3:]
    spec = importlib.util.spec_from_file_location(f.stem, f)
    m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m)
    ui = m.UI
    missing = [k for k in EN if k not in ui]
    extra = [k for k in ui if k not in EN]
    phbad = [k for k in ui if k in EN and set(PH.findall(EN[k])) != set(PH.findall(ui[k]))]
    print(f"{code}: {len(ui)} strings | missing {len(missing)} {missing[:6]} | extra {extra[:4]} | placeholder mismatches {phbad[:6]}")
    bad += len(missing) + len(phbad)
    out[code] = ui
ts = "/* generated by scripts/build_human_ui.py from scripts/human/ui_*.py — do not edit */\nexport const HUMAN: Record<string, Record<string, string>> = " + json.dumps(out, ensure_ascii=False, indent=1) + "\n"
(ROOT / "app" / "src" / "i18n" / "human.ts").write_text(ts, encoding="utf-8")
print("human.ts written:", len(ts) // 1024, "KB")
sys.exit(1 if bad else 0)
