// Post-build step: write dist/sw.js, a tiny cache-first service worker that precaches every built file.
// (Hand-rolled on purpose: ~30 lines, no plugin version drift, easy to audit.)
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, rmSync, statSync, writeFileSync } from 'node:fs'
import { join, relative } from 'node:path'

import { fileURLToPath } from 'node:url'
const dist = fileURLToPath(new URL('../dist', import.meta.url))

function walk(dir) {
  return readdirSync(dir).flatMap((n) => {
    const p = join(dir, n)
    return statSync(p).isDirectory() ? walk(p) : [p]
  })
}

// Vite also emits a hashed copy of the ORT wasm that we never load (wasmPaths points at ./ort/): drop it (-14 MB).
for (const p of walk(dist)) if (/assets[\\/]ort-wasm[^\\/]*\.wasm$/.test(p)) rmSync(p)

const files = walk(dist).map((p) => relative(dist, p).split('\\').join('/')).filter((f) => f !== 'sw.js' && !f.startsWith('data/audio/'))   // voice packs are downloaded on demand
const hash = createHash('sha1')
for (const f of files.sort()) hash.update(f).update(readFileSync(join(dist, f)))
const version = hash.digest('hex').slice(0, 10)
const mb = files.reduce((a, f) => a + statSync(join(dist, f)).size, 0) / 1e6

const sw = `// generated by scripts/gen-sw.mjs - do not edit
const CACHE = 'agriai-${version}'
const FILES = ${JSON.stringify(['./', ...files])}
self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES.map((f) => new Request(f, { cache: 'reload' })))).then(() => self.skipWaiting()))
})
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE && k !== 'agriai-audio').map((k) => caches.delete(k)))).then(() => self.clients.claim()))
})
self.addEventListener('fetch', (e) => {
  if (e.request.method !== 'GET') return
  // voice packs: cache-first from the persistent audio cache (filled by the app's "download voice pack"), network fallback
  if (new URL(e.request.url).pathname.includes('/data/audio/')) {
    e.respondWith(caches.open('agriai-audio').then((c) => c.match(e.request).then((hit) => hit || fetch(e.request))))
    return
  }
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit
      if (e.request.mode === 'navigate') return caches.match('./index.html')
      return fetch(e.request)
    }),
  )
})
`
writeFileSync(join(dist, 'sw.js'), sw)
console.log(`sw.js written: ${files.length} files, ${mb.toFixed(1)} MB precached, version ${version}`)
